<?php

/**
 * @file
 * Contact us.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_mail().
 */
function contact_us_mail($key, &$message, $params) {
  switch ($key) {
    case 'contact_us_notify':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $site_name = \Drupal::config('system.site')->get('name');

      $message['subject'] = $site_name . ": " . t('New contact us form submitted');

      $message_body['name'] = $params['message']['contactusyourname'];
      $message_body['company_name'] = $params['message']['contactuscompanyname'];
      $message_body['designation'] = $params['message']['contactusdesignation'];
      $message_body['address'] = $params['message']['contactusaddress'];
      $message_body['country'] = $params['message']['contactuscountry'];
      $message_body['email'] = $params['message']['contactusemail'];
      $message_body['phone'] = $params['message']['contactusphone'];
      $message_body['query'] = $params['message']['contactusquery'];
      
      /**
       * Assign a twig template for message body
       */
      $message_theme_body = array(
        '#theme' => 'contact_us_notify_email',
        '#message_body' => $message_body,
       );
      
      $message_render = \Drupal::service('renderer')->render($message_theme_body);
      $message['body'][] = Html::escape($message_render);
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed;';
      break;
  }
}

/**
 * Implements hook_theme().
 */
function contact_us_theme($existing, $type, $theme, $path) {
  return [
    'contact_us_notify_email' => [
      'variables' => ['message_body' => NULL],
    ],
  ];
}
